version: '3'
services:
  database:
    image: postgres:14.2-alpine
    environment:
      # Required POSTGRES_*
      - POSTGRES_USER=sevstar
      - POSTGRES_PASSWORD=s3cr3t
      - POSTGRES_DB=sevstar
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      backend:
    restart: always

  daemon:
    image: perl
    environment:
      - POSTGRES_DSN=postgres://sevstar:s3cr3t@database:5432/sevstar
    volumes:
      - ${PWD}:/root/app
    networks:
      backend:
    restart: always
    depends_on:
      - database
    command: bash -c "cpanm --installdeps -n /root/app && perl /root/app/daemon.pl"
    
  app:
    image: perl
    environment:
      # Optional
      - POSTGRES_DSN=postgres://sevstar:s3cr3t@database:5432/sevstar
      - MOJO_IOLOOP_DEBUG=1
      - MOJO_INSECURE=1
    volumes:
      - uploads:/root/app/public/uploads
      - ${PWD}:/root/app
    ports:
      - "80:80"
    networks:
      backend:
    restart: always
    depends_on:
      - database
    command: bash -c "cpanm --installdeps -n /root/app && MOJO_MODE=development morbo -v -w /root/app/app.conf -w /root/app/templates -w /root/app/public /root/app/web.pl -l http://*:80 && tail -f /root/app/app.log"
    # command: bash -c "cpanm --installdeps -n /root/app && perl /root/app/daemon.pl && hypnotoad -f /root/app/web.pl"

networks:
  backend:

volumes:
  database:
  uploads:
