version: '3'
services:
  database:
    image: postgres:14.2-alpine
    environment:
      - POSTGRES_USER=sevstar
      - POSTGRES_PASSWORD=s3cr3t
      - POSTGRES_DB=sevstar
    volumes:
      - database:/var/lib/postgresql/data
    networks:
      backend:
    restart: always
  app:
    build:
      context: .
    image: perl
    environment:
      - POSTGRES_DSN=postgres://sevstar:s3cr3t@database:5432/sevstar
      - MOJO_IOLOOP_DEBUG=1
      # - MOJO_MODE=development
    volumes:
      - ${PWD}:/root/app
    ports:
      - "80:80"
    networks:
      backend:
    restart: always
    depends_on:
      - database
    links:
      - database
    command: bash -c "morbo -v -w /root/app/app.conf -w /root/app/templates -w /root/app/public /root/app/web.pl -l http://*:80"
  daemon:
    build: 
      context: .
    image: perl
    environment:
      - POSTGRES_DSN=postgres://sevstar:s3cr3t@database:5432/sevstar
      - MOJO_IOLOOP_DEBUG=1
      # - MOJO_CLIENT_DEBUG=1
      - MOJO_INSECURE=1
    volumes:
      - uploads:/root/app/public/uploads
      - ${PWD}:/root/app
    networks:
      backend:
    restart: always
    depends_on:
      - database
      - app
    links:
      - database
    command: perl /root/app/daemon.pl

networks:
  backend:

volumes:
  database:
  uploads:
